const userTypes = {
    // AUTH
    USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
    USER_SIGN_IN_SUCCESS: "USER_SIGN_IN_SUCCESS",
    USER_RECOVERY_SUCCESS: "USER_RECOVERY_SUCCESS",
    OUT_CURRENT_USER: "OUT_CURRENT_USER",
    // RESET FORM
    RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
    RESET_ERRORSSTATE_FORMS: "RESET_ERRORSSTATE_FORMS",
    RESET_STATES: "RESET_STATES",
    // USER
    SET_USER: "SET_USER",
    SET_USER_DOC_ID: "SET_USER_DOC_ID",
    // ERROR
    SET_ERRORS: "SET_ERRORS",
  };
  
  export default userTypes;